"""Initial schema: catalog, governance, observations and jobs.

Creates the foundational tables required by `tasks.md` 1.3: instruments,
listings, external identities, versioned policies/evidence, append-only
observations, and jobs. Reversible on PostgreSQL and SQLite (uses "batch
mode" for indexes on SQLite).

Revision ID: 0001
Revises:
Create Date: 2026-09-02 00:03:25.203794

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instruments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "asset_class",
            sa.Enum(
                "EQUITY", "ETF", "FUND", "CRYPTO", name="assetclass", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("isin", sa.String(length=12), nullable=True),
        sa.Column("figi", sa.String(length=12), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instruments")),
        sa.UniqueConstraint("isin", name="uq_instruments_isin"),
    )
    op.create_table(
        "source_policy_decisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column(
            "capability",
            sa.Enum(
                "RETRIEVE",
                "STORE",
                "DISPLAY",
                "REDISTRIBUTE",
                "ATTRIBUTE",
                "RETAIN",
                name="policycapability",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "APPROVED",
                "DENIED",
                "UNRESOLVED",
                name="policystatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("evidence_reference", sa.String(length=512), nullable=False),
        sa.Column("reviewed_by", sa.String(length=128), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(), nullable=False),
        sa.Column("notes", sa.String(length=1024), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_policy_decisions")),
        sa.UniqueConstraint(
            "source", "capability", "version", name="uq_source_policy_source_cap_version"
        ),
    )
    with op.batch_alter_table("source_policy_decisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_source_policy_decisions_source"), ["source"], unique=False
        )

    op.create_table(
        "listings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("mic", sa.String(length=4), nullable=True),
        sa.Column("venue", sa.String(length=64), nullable=False),
        sa.Column("ticker", sa.String(length=32), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_listings_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listings")),
        sa.UniqueConstraint(
            "instrument_id", "venue", "ticker", "currency", name="uq_listings_venue_ticker_ccy"
        ),
    )
    with op.batch_alter_table("listings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_listings_instrument_id"), ["instrument_id"], unique=False
        )

    op.create_table(
        "external_identities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("listing_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to >= valid_from",
            name=op.f("ck_external_identities_valid_to_after_valid_from"),
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_external_identities_listing_id_listings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_identities")),
        sa.UniqueConstraint(
            "source", "external_id", "valid_from", name="uq_external_identities_source_ext_from"
        ),
    )
    with op.batch_alter_table("external_identities", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_external_identities_listing_id"), ["listing_id"], unique=False
        )

    op.create_table(
        "jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_type", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("listing_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "CLAIMED",
                "RUNNING",
                "WAITING_FOR_PUBLICATION",
                "DONE",
                "FAILED",
                name="jobstatus",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("cursor", sa.String(length=512), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("next_run_at", sa.DateTime(), nullable=False),
        sa.Column("claimed_by", sa.String(length=128), nullable=True),
        sa.Column("claimed_at", sa.DateTime(), nullable=True),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.String(length=1024), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_jobs_listing_id_listings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jobs_listing_id"), ["listing_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_source"), ["source"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_status"), ["status"], unique=False)

    op.create_table(
        "observations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("listing_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("credential_scope", sa.String(length=64), nullable=False),
        sa.Column("external_listing_id", sa.String(length=128), nullable=False),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column(
            "observation_type",
            sa.Enum("EOD_CLOSE", "NAV", name="observationtype", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("close", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("open", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("high", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("low", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("adjusted_close", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column(
            "quality_status",
            sa.Enum("OK", "SUSPECT", name="qualitystatus", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("retrieved_at", sa.DateTime(), nullable=False),
        sa.Column("is_publishable", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_observations_listing_id_listings"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_observations")),
        sa.UniqueConstraint(
            "source",
            "credential_scope",
            "external_listing_id",
            "session_date",
            "observation_type",
            name="uq_observations_idempotency_key",
        ),
    )
    with op.batch_alter_table("observations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_observations_listing_id"), ["listing_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("observations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_observations_listing_id"))

    op.drop_table("observations")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_jobs_source"))
        batch_op.drop_index(batch_op.f("ix_jobs_listing_id"))

    op.drop_table("jobs")
    with op.batch_alter_table("external_identities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_external_identities_listing_id"))

    op.drop_table("external_identities")
    with op.batch_alter_table("listings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_listings_instrument_id"))

    op.drop_table("listings")
    with op.batch_alter_table("source_policy_decisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_source_policy_decisions_source"))

    op.drop_table("source_policy_decisions")
    op.drop_table("instruments")
    # ### end Alembic commands ###
